language: python
python:
- '3.4'
- '3.5'
install:
- pip install pytest
- pip install pytest-pep8
script:
    - py.test --pep8 .
    - make
deploy:
  provider: releases
  api_key:
    secure: gHK6P++e5DRy9N8XiBR4eEdjHuAQRFVEeZHXOpGeD8shub4flK/61SzR3mQWsPViRbPltz+vku2P7PewQtwxAQpOyyajCengHhv804udqQgEtB62J4VxPiBZ7Wzhl6m8Zxws+fklXmTN7W/g1dVkh5OprC2EtydRrpZTrAQqpIYux1Udux0isKQT0KivwXpxBiVDOmuBEyVHFVsPPtR1GACMLQBrkPGgA4r7hlGjJ0ttK1dQb7tzqreHEQLj6V3cpGxnipBEOxohHOSXFfzvOCyOE1bIDdxCgikC+koRo4Xtv3oaNxwtPZV7Ol30gOgsG9fVNrl1pqx/gzqZH4ha4o7opa9sw9INLFoLLdtM0N4JVFc1s1Ag2rh+Pm557CC58bUv+ihushd0CKjH08O4SCJcGxTWKVOkL2npCIs2UZEWkBKfpmOLchb8v/c2FXha1oblfRsNZdLAseWUraKSY4CMYAVolO7Uwfz9Dhmf8DZWQB1RLWCTeEhV5flF2Hd70mVqNeSoGVgtJiNwI+bm+wnlpEDzVjm+Bdlmf4LScfA1s3FWG7GK1YfdI1m2kHo6VDQlqwXbM+Lz6r7pe5TP4Ox2CToADZGvL46O87/taYnl4egpkV+CI0bdQr9DyeKHoRYL5DvfmjInMg5p7QNXB+AA82DaQ2Uv5RgtTKK0x/4=
  file_glob: true
  file: "*.deb"
  skip_cleanup: true
  on:
    tags: true
    repo: shaggytwodope/nixcontrolcenter
